travis:
  secure:
    BINSTAR_TOKEN: boZvLsIeWYw5pnE1prW4wZNBWggeRHPcJ3x87U4aqnqHKtpRNqJCz7p/LUwKq3g8v1k6qCfGxt7h4TkigPPOTiU+RZW/KRNQIwZFdMHtRZnGy0a/d1FVSLsEDcXqMtlRMAMCP/gkJ4Ul+77Jn98n+eSYjrayF7ua7/K85TKVI15gKtMI0bUQGdpg909/DIx4Vser1czkRjjuJSBlxSHc8M1stKlW2Yg8Off3GzST/eg2YTAThBsi9t05g2TWMuJqvTnAWIa3WIFWbxiXyJ2s0rp7SPem3FYEB0+UAgy7D5AmYEm9QeLT+f3B3VcLhaKGe9zPluUyDk5GHbTBQ89irCjwx3et1zc58q6o+A6I/kwFMrBXXdP3R4lCPMJ/r+RKm+Hqt4/Rcti3Kbkd20ju/rlXElV+EOwUS7bX76N0TueJy8P+yUTUUc3MfffxSZl6SVWIddNkJs6RAMfhAC2kwRBWwEZLsKbCqucrB5E3RK77iajoAMxDekLJletk/pJIqVmPDCOI5yxkfxfSumZ2i15Lh5fkLByf9kUJ45Vkxyci/6OKc1CH1HDsTmrDo/qr3umQdoNb9shhcnlU4x8MlOVUuCR4hc3dW4Gp5t1SUjS4jxXbAK1LN3Y/2oVYjrRK5PK28sF3tr/eE6F959GHkxv+CAcCbl1gz1MgKGi82os=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
