travis:
  secure:
    BINSTAR_TOKEN: ZEHChbXlvZIY/g8mPXSvC+6VM6ONHsQ2MqiUumuTA5xUShWZxw6DZGEHhrWbmUyTIYnZ9Vv2Yz00WPDJWCxXDFx5YGUUWcbR0E8vVNfxku1LSVHJqWoYSWkchIziLf3kCTGC3eVrC1UB8VwzLyXyh1ZWdz0bTGNZ0JhNxpc5CBwD7GHZFHulMFsAYeapqBQhUUP2++sYX5cxb/1Ei+ALl9xUaRWxQEDTTLuE8ZURJ0htnK9yIgeQqI6v3zXC49QArvgri2Vr9xI3nGk+Pt9Y8CFC+ptX/888cXmOQ06Y0Y+YEOGY0wuStrl3k7ik3fW8VMwlHsH79f7s4uM7YGubKAWuEm1sXoJfMP21x1RQFF0/lx2qwbIVC2Wn/VUXM78C2hU6c98ptaFdcZz5C7rzNesNr5OrKxLmAmmKAzEP2LDVApx0gUvyOho6rqWCtVKAtgcgwFkDUIhNmO2q6f5OuhhrsKiFF6ApzVeUvTlbdSX/BvJ2nKw+oURRXNG4wcfzVrLl4MCANfbJGMldrmjA1W/lx5m70cbH1Jkfrzk2sxkIZW7S+fTtn70gnvm6Abipj/G/OewN08BH2AVXiF7tYFxXwEFJlAhsi16B7X9ONbIf3yfS9xbSBcsj/jHtmdF9j0oqHh90YVdlOyrLsR2ykaKenVF5jQEZ8mXjOLAjIEk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
